#!/bin/bash

# Slackware build script for Gaviota Chess Engine

# Copyright 2020 Giorgio Peron Campodarsego, PD, Italy giorgio.peron@gmail.com
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=gaviota
VERSION=${VERSION:-1.0}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

case "$( uname -m )" in
  i?86) ARCH=i686 ;;
  arm*) ARCH=arm ;;
     *) ARCH=$( uname -m ) ;;
esac

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

if [ "$ARCH" = "i486" ]; then
#  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
  SUFFIXNAME="32"
elif [ "$ARCH" = "i686" ]; then
#  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
  SUFFIXNAME="32"
elif [ "$ARCH" = "x86_64" ]; then
#  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
  SUFFIXNAME="64"
else
#  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
  SUFFIXNAME="32"
fi

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
#
# gaviota chess engine
#
tar xvf $CWD/$PRGNAM-$VERSION-linux.tar.gz
cd $PRGNAM-$VERSION-linux
chown -R root:root .
find . ! -type l    -a \
  \(     -perm /111 -a ! -perm 755 -a -exec chmod -f 755 {} + \) -o \
  \(   ! -perm /111 -a ! -perm 644 -a -exec chmod -f 644 {} + \)

# install manually
mkdir -p $PKG/usr/share/$PRGNAM
cp -r * $PKG/usr/share/$PRGNAM/
# move the docs to our standard location first
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
mv $PKG/usr/share/$PRGNAM/readme.txt $PKG/usr/doc/$PRGNAM-$VERSION
mv $PKG/usr/share/$PRGNAM/license $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
# binary
mkdir -p $PKG/usr/bin
cd $PKG/usr/bin
ln -sf ../share/$PRGNAM/$PRGNAM-$VERSION-linux$SUFFIXNAME $PRGNAM
#
# tbprobe 0.4.5
#
cd $TMP
rm -rf Gaviota-Tablebases-981472cc83e3a8b6e996191e564295609ea4ce30
unzip $CWD/Gaviota-Tablebases-981472cc83e3a8b6e996191e564295609ea4ce30.zip
cd Gaviota-Tablebases-981472cc83e3a8b6e996191e564295609ea4ce30
chown -R root:root .
find . ! -type l    -a \
  \(     -perm /111 -a ! -perm 755 -a -exec chmod -f 755 {} + \) -o \
  \(   ! -perm /111 -a ! -perm 644 -a -exec chmod -f 644 {} + \)
sed -i "s:PREFIX = /usr/local:PREFIX = ${PKG}/usr:g" Makefile
sed -i "s:\$(PREFIX)/lib:${PKG}/lib${LIBDIRSUFFIX}:g" Makefile
mkdir -p $PKG/lib${LIBDIRSUFFIX}
mkdir -p $PKG/usr/include
make
make install DESTDIR=$PKG
./compile.sh
cp tbprobe $PKG/usr/share/$PRGNAM
# Move the docs to our standard location first
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/tbprobe
cp -a *.txt $PKG/usr/doc/$PRGNAM-$VERSION/tbprobe
# Binary
cd $PKG/usr/bin
ln -sf ../share/$PRGNAM/tbprobe tbprobe
#
# tbtool
#
cd $TMP
rm -rf tbtools-linux32
tar xvzf $CWD/tbtools-linux32.tar.gz
cd tbtools-linux32
chown -R root:root .
find . ! -type l    -a \
  \(     -perm /111 -a ! -perm 755 -a -exec chmod -f 755 {} + \) -o \
  \(   ! -perm /111 -a ! -perm 644 -a -exec chmod -f 644 {} + \)
cp {tbcheck,tbcp} $PKG/usr/share/$PRGNAM/
# Move the docs to our standard location first
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/tbtools
cp -a licenses $PKG/usr/doc/$PRGNAM-$VERSION/tbtools
cd $PKG/usr/bin
ln -sf ../share/$PRGNAM/tbcheck tbcheck
ln -sf ../share/$PRGNAM/tbcp tbcp
#
# Ordo 1.2.6
#
cd $TMP
rm -rf Ordo-1.2.6
tar xvzf $CWD/Ordo-1.2.6.tar.gz
# Move the docs to our standard location first
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/ordo
cd Ordo-1.2.6
cp -a INSTALL.txt LICENSE.txt README.md $PKG/usr/doc/$PRGNAM-$VERSION/ordo
chown -R root:root .
find . ! -type l    -a \
  \(     -perm /111 -a ! -perm 755 -a -exec chmod -f 755 {} + \) -o \
  \(   ! -perm /111 -a ! -perm 644 -a -exec chmod -f 644 {} + \)
sed -i "s:/usr/local/bin/\$(EXE):$PKG/usr/share/$PRGNAM/\$(EXE):g" Makefile
make
make install
cd $PKG/usr/bin
ln -sf ../share/$PRGNAM/ordo ordo
#
# Gaviota Big Book 
#
cd $PKG/usr/share/$PRGNAM
unzip $CWD/gavibook.bin.zip
cd -

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

# final fix
cd $PKG/lib$LIBDIRSUFFIX
ln -sf libgtb.so.1.0.1 libgtb.so
cd -
chmod 644 $PKG/usr/doc/gaviota-1.0/license/gaviota-engine-license.txt
chmod 644 $PKG/lib$LIBDIRSUFFIX/libgtb.a


mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -c n -l y $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
